AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DnDCloudCompagnon

  Sample SAM Template for DnDCloudCompagnon

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SpellsApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: spells-api/
      Handler: app.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        ListSpells:
          Type: HttpApi
          Properties:
            Path: /spells
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - app.ts

  SpellsApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SpellsApiFunction}"
      RetentionInDays: 7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpellsApiFunction:
    Description: "Spells API Lambda Function ARN"
    Value: !GetAtt SpellsApiFunction.Arn
  SpellsApiFunctionIamRole:
    Description: "Implicit IAM Role created for the Spells API function"
    Value: !GetAtt SpellsApiFunctionRole.Arn
