###
GET http://localhost:3000/feats
    ?category=general


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");

    });
    client.test("All feats are don général", function () {
        client.assert(Array.isArray(response.body.feats), "feats is not an array");
        const nonMatchingFeats = response.body.feats.filter(feat => feat.Category !== "don général");
        client.assert(nonMatchingFeats.length === 0, "Some feats are not don général");
    });
%}
###

GET http://localhost:3000/feats/chanceux

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Body has a self link", function () {
        client.assert(response.body.hasOwnProperty("_self"), "missing self link");
    });
%}
###
