###
GET http://localhost:3000/api/v1/spells
    ?level=0&class=Clerc


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");

    });
    client.test("All spells are level 0", function () {
        client.assert(Array.isArray(response.body.spells), "spells is not an array");
        const nonLevelZeroSpells = response.body.spells.filter(spell => spell.Level !== 0);
        client.assert(nonLevelZeroSpells.length === 0, "Some spells are not level 0");
    });
%}
###

GET http://localhost:3000/api/v1/spells/flamme-sacree

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Body has a self link", function () {
        client.assert(response.body.hasOwnProperty("_self"), "missing self link");
    });
%}
###
